# MPLAB IDE generated this makefile for use with GNU make.
# Project: Refresh_display.mcp
# Date: Sat Nov 12 18:23:43 2022

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

Refresh_display.cof : Refresh_display.o
	$(CC) /p16F877A "Refresh_display.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"Refresh_display.cof" /M"Refresh_display.map" /W

Refresh_display.o : ../Refresh_display.ASM ../../../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/p16f877A.inc
	$(AS) /q /p16F877A "C:\Users\Gaspar\Lab-3-SD\Refresh_Display\Refresh_display.ASM" /l"Refresh_display.lst" /e"Refresh_display.err" /o"Refresh_display.o" /d__DEBUG=1

clean : 
	$(CC) "Refresh_display.o" "Refresh_display.err" "Refresh_display.lst" "Refresh_display.cof" "Refresh_display.hex"

